/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package z3;

import z3.LocalSearch.FirstSolution.ProperSolution;
import z3.LocalSearch.LocalSearch;
import z3.LocalSearch.Neighborhood.SimplifyNeighborhood;
import z3.LocalSearch.PathFunction;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        InputParser ip = new InputParser();
        ArrayList<ArrayList<Integer>> board = ip.getInput();
        int maxTime = ip.getMaxTime();
        PathFunction pathFunction = new PathFunction(board);

        LocalSearch ls = new LocalSearch(pathFunction, new ProperSolution(), new SimplifyNeighborhood());
        ArrayList<String> result = ls.search(maxTime);

        //OUTPUT
        System.out.println(pathFunction.compute(result));
        for (String s : result) {
            System.err.print(s);
        }
        System.err.println();
    }
}
